### PR TITLE
fix confusing error message with list-patches

### LINKED ISSUE #102: list-patches: confusing error message when using `--severity` flag
If one runs `zypper-docker lp --severity low opensuse:latest`, for example, and the host does not have this image, the error message `the --severity flag is only available for zypper versions >= 1.12.6` is printed.
It should instead print `Error: No such image: opensuse:latest` as is done when not using `--severity`.

### PR DESCRIPTION
**Pull request by monstermunchkin**
When using the `--severity` flag with list-patches, a correct error
message is presented when e.g. the image is not available.
The error message indicating an old zypper version is only shown if that
is actually the case.

Fixes #102

Signed-off-by: Thomas Hipp <thipp@suse.com>

### CODE REVIEW

File: patches.go [hunk 1]
```diff
@@ -37,9 +37,15 @@ func listPatchesContainerCmd(ctx *cli.Context) {
 // arguments.
 func listPatches(image string, ctx *cli.Context) {
 	if severity := ctx.String("severity"); severity != "" {
-		if !supportsSeverityFlag(image) {
-			log.Println("the --severity flag is only available for zypper versions >= 1.12.6")
-			fmt.Println("the --severity flag is only available for zypper versions >= 1.12.6")
+		ok, err := supportsSeverityFlag(image)
+		if !ok {
```
Comment (mssola) [inline patches.go]: Nitpicking: `if ok, err := supportsSeverityFlag(image); !ok {`

**Comment by mssola** [comment]
LGTM :+1:

File: patches.go (hunk 1 above)
Comment (monstermunchkin) [inline patches.go]: Fixed.

**Comment by mssola** [comment]
Thanks :clap:
