### PR TITLE
Fix update behavior when getting a zypper-related update

### LINKED ISSUE #110: Patch/update should be executed once if there was a zypper update
Right now, if in the list of patches/updates to be applied there's at least one concerning to zypper, the update/patching will be done first for zypper and then exit with a specific exit code (thus, not applying other updates/patches that might be available).

zypper-docker should be able to detect this case, and execute patch/update again whenever a zypper update/patch has been applied.

### PR DESCRIPTION
**Pull request by lightlace**
Fix the semantics of 'client.go', so that a second update process is executed, when a zypper-related update (with exitcode 103) was installed.
Change the explanation of the update process in the manpage.

Fix #110 .

Signed-off-by: Fabian Baumanis <fabian.baumanis@suse.com>

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -180,7 +180,27 @@ func runStreamedCommand(img, cmd string, getError bool) error {
...
+
+	run_cmd:
+		id, err = startContainer(id, cmd, true, dst)
+		return id, err
+		switch err.(type) {
+		case dockerError:
+			de := err.(dockerError)
+			if isZypperExitCodeSevere(de.exitCode) {
+				if de.exitCode == zypperExitInfRestartNeeded  {
+					goto run_cmd
```
Comment (mssola) [inline client.go]: I'm sure you can avoid using a `goto` statement 😉

File: client.go [hunk 2]
```diff
@@ -180,7 +180,27 @@ func runStreamedCommand(img, cmd string, getError bool) error {
...
+	id, err := createContainer(img, cmd)
+	if err != nil {
+		log.Println(err)
+		return "", err
+	}
+
+	run_cmd:
+		id, err = startContainer(id, cmd, true, dst)
+		return id, err
+		switch err.(type) {
```
Comment (mssola) [inline client.go]: Is this going to be called at all ? (mind the previous return statement)

File: client.go (hunk 1 above)
Comment (vrothberg) [reply client.go]: I prefer using a goto here. Golang doesn't support do-while loops, so an alternative to it would be using a for loop and variable indicating another run.

File: client.go [hunk 3]
```diff
@@ -180,7 +180,26 @@ func runStreamedCommand(img, cmd string, getError bool) error {
...
+	}
+
+run_cmd:
+	id, err = startContainer(id, cmd, true, dst)
+	switch err.(type) {
+	case dockerError:
+		de := err.(dockerError)
+		if isZypperExitCodeSevere(de.exitCode) {
+			if de.exitCode == zypperExitInfRestartNeeded {
+				goto run_cmd
```
Comment (vrothberg) [inline client.go]: The nesting of those if-branches isn't correct here. First, we need to return an error if the exit code is severe. Also the zypperExitInfRestartNeeded has the value 103, but severe ones are `> 0 && < 100`, so the if conditions are contradicting. What we should do instead is to return an error if the code is severe and move the run_cmd in a separate if branch.

File: client.go [hunk 4]
```diff
@@ -180,7 +182,27 @@ func runStreamedCommand(img, cmd string, getError bool) error {
...
 // Note well: the container is NOT deleted when the given command terminates.
 func runCommandInContainer(img string, cmd []string, dst io.Writer) (string, error) {
-	return startContainer(img, cmd, true, dst)
+	id, err := createContainer(img, cmd)
+	if err != nil {
+		log.Println(err)
+		return "", err
+	}
+
+run_cmd:
```
Comment (mssola) [inline client.go]: Use a regular `for` loop with a boolean value or something else. Please refrain from using a `goto` statement unless it's *really* necessary.

File: client.go [hunk 5]
```diff
@@ -196,15 +218,10 @@ func runCommandInContainer(img string, cmd []string, dst io.Writer) (string, err
 // returned can be of type dockerError. This only happens when the container
 // has run normally (no signals, no timeout), but the exit code is not 0. Read
 // the documentation on the `dockerError` command on why we do this.
-func startContainer(img string, cmd []string, wait bool, dst io.Writer) (string, error) {
-	id, err := createContainer(img, cmd)
-	if err != nil {
-		log.Println(err)
-		return "", err
-	}
+func startContainer(id string, cmd []string, wait bool, dst io.Writer) (string, error) {
```
Comment (mssola) [inline client.go]: Update the documentation as @vrothberg said. The semantics have changed, so the expectation has changed too, and the documentation should be in sync with the semantics.

File: client.go [hunk 6]
```diff
@@ -180,31 +183,50 @@ func runStreamedCommand(img, cmd string, getError bool) error {
...
 func runCommandInContainer(img string, cmd []string, dst io.Writer) (string, error) {
-	return startContainer(img, cmd, true, dst)
+	id, err := createContainer(img, cmd)
+	if err != nil {
+		log.Println(err)
+		return "", err
+	}
+
+	error103 := false
+	for error103 == false {
```
Comment (mssola) [inline client.go]: `for !error103 {`

Comment (vrothberg) [reply client.go]: I prefer a more intuitive identifier, for instance `runCommand` or `execute` or something that indicates the semantics behind.

Comment (lightlace) [reply client.go]: @mssola let me explain my thoughts on this:

error103 is false, so 'startContainer' is executed the first time.
Now we assume, a 103 exitcode was returned.
So, he leaves error103 on false and startCommand will be executed again.
Now we assume, no exitcode 103 was returned.
Therefore we go in fo the default case, where error103 is set to true and startCommand won't be executed again.

If there are more zypper updates which return the exitcode 103, the for-loop runs until there is no exitcode 103 anymore.

Comment (lightlace) [reply client.go]: BTW, i changed error103 to 'execute' as @vrothberg mentioned before.
Therefore, startCommand will be executed, as long as 'execute' is 'true'.

File: man/zypper-docker-up.1.md [hunk 7]
```diff
@@ -9,9 +9,11 @@ zypper\-docker update \- Install the available updates for the given image.
 
 # DESCRIPTION
 The **update** command updates the given openSUSE/SUSE Linux Enterprise image
-with all the available updates. The updated image will have a new name, as
-provided by the NEW-IMAGE argument. Note that both the IMAGE and the NEW\-IMAGE
-arguments have to follow Docker's naming format.
+with all the available updates. If there is a zypper-related update, which returns
+the exit code 103 (zypperExitInfRestartNeeded), zypper-docker goes through the
```
Comment (vrothberg) [inline man/zypper-docker-up.1.md]: The actual exit code of zypper is called `ZYPPER_EXIT_INF_RESTART_NEEDED` (see zypper's manpages). After that change, I think we're good to go :+1:

Comment (lightlace) [reply man/zypper-docker-up.1.md]: ok, will change that

File: client.go [hunk 8]
```diff
@@ -180,31 +183,50 @@ func runStreamedCommand(img, cmd string, getError bool) error {
...
+				return "", err
+			}
+			if de.exitCode == zypperExitInfRestartNeeded {
+				execute = true
+			}
+		default:
+			execute = false
+			return id, err
+		}
+		return id, err
```
Comment (cyphar) [inline client.go]: Doesn't this line mean the loop will never run more than once?

File: client.go [hunk 9]
```diff
@@ -180,31 +183,50 @@ func runStreamedCommand(img, cmd string, getError bool) error {
...
 func runCommandInContainer(img string, cmd []string, dst io.Writer) (string, error) {
-	return startContainer(img, cmd, true, dst)
+	id, err := createContainer(img, cmd)
+	if err != nil {
+		log.Println(err)
+		return "", err
+	}
+
+	execute := true
+	for execute {
```
Comment (cyphar) [inline client.go]: To avoid infinite loops we could do something like

```
for i := 0; i < 256; i++ {
  // snip: startContainer
  switch err.(type) {
  case dockerError:
    // snip: the severe check
    if de.exitCode == zypperExitInfRestartNeeded {
      continue
    }
  default:
  }
  return id, err
}
return "", some_error_about_too_many_retries
```

File: client.go (hunk 8 above)
Comment (lightlace) [reply client.go]: which one? the "return id, err" ?

Comment (cyphar) [reply client.go]: Line 208. To me it looks like:

```
for someCond {
  // some code
  return blah
}
```

Which will always return `blah` (you need to use `continue` or similar to make the loop not hit that `return` statement).

**Comment by lightlace** [comment]
ping please review @cyphar  @vrothberg @mssola

File: client.go (hunk 5 above)
Comment (vrothberg) [reply client.go]: `startContainer(...)` currently doesn't use the `cmd` argument. We need to fix as the interface suggests that passed `cmd` will actually be executed inside container `id`. Sorry for not catching this before.

Comment (cyphar) [reply client.go]: Yeah, `cmd` shouldn't be passed now that we mirror the `create`-`start` API.

**Comment by lightlace** [comment]
Changes in client.go: removed the argument 'cmd' from the function 'startContainer' and from all elements which call 'startContainer'

**Comment by vrothberg** [comment]
@mssola Any remaining or new objections?

**Comment by lightlace** [comment]
this PR is still open, anything still wrong with it, or can it be merged?

@mssola @cyphar @vrothberg
